import { StyleSheet } from 'react-native';
import { designTokens } from '@boomerbuddy/design';

const c = designTokens.colors;
const s = designTokens.spacing;

export const appStyles = StyleSheet.create({
  safe: { backgroundColor: c.canvas, flex: 1 },
  screen: {
    alignSelf: 'center',
    backgroundColor: c.canvas,
    flexGrow: 1,
    gap: s.md,
    maxWidth: 840,
    padding: s.md,
    width: '100%',
  },
  title: { color: c.primaryHover, fontSize: 34, fontWeight: '700', lineHeight: 41 },
  heading: { color: c.primaryHover, fontSize: 24, fontWeight: '700', lineHeight: 30 },
  body: { color: c.text, fontSize: designTokens.typography.bodyPx, lineHeight: 28 },
  muted: { color: c.textMuted, fontSize: designTokens.typography.smallPx, lineHeight: 23 },
  label: { color: c.primaryHover, fontSize: designTokens.typography.bodyPx, fontWeight: '700' },
  card: {
    backgroundColor: c.surface,
    borderColor: c.border,
    borderRadius: designTokens.radii.medium,
    borderWidth: 1,
    gap: s.sm,
    padding: s.md,
  },
  button: {
    alignItems: 'center',
    borderRadius: designTokens.radii.medium,
    justifyContent: 'center',
    minHeight: designTokens.targets.comfortablePx,
    paddingHorizontal: s.md,
    paddingVertical: s.sm,
  },
  buttonPrimary: { backgroundColor: c.primary },
  buttonSecondary: { backgroundColor: c.surface, borderColor: c.primary, borderWidth: 2 },
  buttonDanger: { backgroundColor: c.surface, borderColor: c.highConcern, borderWidth: 2 },
  buttonDisabled: { opacity: 0.55 },
  buttonTextPrimary: {
    color: c.onPrimary,
    fontSize: designTokens.typography.bodyPx,
    fontWeight: '700',
    textAlign: 'center',
  },
  buttonTextSecondary: {
    color: c.primary,
    fontSize: designTokens.typography.bodyPx,
    fontWeight: '700',
    textAlign: 'center',
  },
  buttonTextDanger: {
    color: c.highConcern,
    fontSize: designTokens.typography.bodyPx,
    fontWeight: '700',
    textAlign: 'center',
  },
  input: {
    backgroundColor: c.surface,
    borderColor: c.border,
    borderRadius: designTokens.radii.medium,
    borderWidth: 2,
    color: c.text,
    fontSize: designTokens.typography.bodyPx,
    minHeight: designTokens.targets.comfortablePx,
    padding: s.md,
  },
  textarea: { minHeight: 180, textAlignVertical: 'top' },
  banner: {
    backgroundColor: c.warningSurface,
    borderColor: c.caution,
    borderRadius: designTokens.radii.medium,
    borderWidth: 1,
    gap: s.xs,
    padding: s.md,
  },
  scopeBanner: {
    backgroundColor: c.surface,
    borderBottomColor: c.border,
    borderBottomWidth: 1,
    gap: s.xs,
    padding: s.sm,
  },
  error: {
    backgroundColor: c.dangerSurface,
    borderColor: c.highConcern,
    borderLeftWidth: 6,
    color: c.highConcern,
    fontSize: designTokens.typography.bodyPx,
    padding: s.md,
  },
  row: { flexDirection: 'row', flexWrap: 'wrap', gap: s.sm },
  navGrid: { gap: s.sm },
  choice: {
    alignItems: 'center',
    backgroundColor: c.surface,
    borderColor: c.border,
    borderRadius: designTokens.radii.medium,
    borderWidth: 2,
    flexDirection: 'row',
    gap: s.sm,
    minHeight: designTokens.targets.comfortablePx,
    padding: s.md,
  },
  choiceSelected: { borderColor: c.primary, borderWidth: 3 },
  radio: { borderColor: c.primary, borderRadius: 10, borderWidth: 2, height: 20, width: 20 },
  radioSelected: { backgroundColor: c.primary, borderColor: c.surface, borderWidth: 4 },
  risk: { borderLeftWidth: 8 },
  riskCaution: { borderLeftColor: c.caution },
  riskHigh: { borderLeftColor: c.highConcern },
  riskUnknown: { borderLeftColor: c.unknown },
  pill: {
    alignSelf: 'flex-start',
    backgroundColor: c.surfaceMuted,
    borderRadius: designTokens.radii.pill,
    color: c.primaryHover,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.5,
    overflow: 'hidden',
    paddingHorizontal: s.sm,
    paddingVertical: s.xs,
    textTransform: 'uppercase',
  },
  divider: { backgroundColor: c.border, height: 1 },
});
